default_stages: [commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - entry: check-toml
        id: check-toml
        language: system
        name: Check Toml
        types:
          - toml
      - args:
          - --unsafe
        entry: check-yaml
        id: check-yaml
        language: system
        name: Check Yaml
        types:
          - yaml
        exclude: |
          (?x)^(
              {{cookiecutter.project_name}}/docs/|
              {{cookiecutter.project_name}}/.aws/ecs.yml|
              {{cookiecutter.project_name}}/docker-compose.yml
          )
      - entry: end-of-file-fixer
        id: end-of-file-fixer
        language: system
        name: Fix End of Files
        types:
          - text
      - entry: trailing-whitespace-fixer
        id: trailing-whitespace
        language: system
        name: Trim Trailing Whitespace
        types:
          - text
  - repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
      - entry: black
        id: black
        name: black
        require_serial: true
        types:
          - python
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - entry: flake8
        id: flake8
        language: system
        name: flake8
        require_serial: true
        types:
          - python
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.6.0
    hooks:
      - args:
          - --application-directories=src
        entry: reorder-python-imports
        id: reorder-python-imports
        language: system
        name: Reorder python imports
        types:
          - python
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.4.1
    hooks:
      - id: prettier
        entry: prettier --write --list-different --ignore-unknown
        exclude: |
          (?x)^(
              {{cookiecutter.project_name}}/docs/|
              {{cookiecutter.project_name}}/.aws/ecs.yml|
              {{cookiecutter.project_name}}/docker-compose.yml|
              CHANGELOG.md
          )
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.20.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
