name: learn-github-actions
on:
  push:
    branches:
      - main
jobs:
  check-poetry-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.11
      - name: View poetry --help
        run: poetry --help
